# add the linters you want stickler to use for this project
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:

# add the files here you want to be ignored by stylelint
files:
  ignore:
      - 'dist/*'

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs

